package org.tempuri.zmlq_xsd.service_wsdl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-02-15T22:02:46.283+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/ZMLQ.xsd/Service.wsdl", name = "ServicePortType")
@XmlSeeAlso({org.tempuri.zmlq.ObjectFactory.class})
public interface ServicePortType {

    /**
     * Service definition of function ZMLQ__GetReaderStatus
     */
    @WebResult(name = "in-strStatus", targetNamespace = "")
    @RequestWrapper(localName = "GetReaderStatus", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetReaderStatus")
    @WebMethod(operationName = "GetReaderStatus")
    @ResponseWrapper(localName = "GetReaderStatusResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetReaderStatusResponse")
    public java.lang.String getReaderStatus(
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID
    );

    /**
     * Service definition of function ZMLQ__Init
     */
    @WebResult(name = "out-initResult", targetNamespace = "")
    @RequestWrapper(localName = "Init", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.Init")
    @WebMethod(operationName = "Init")
    @ResponseWrapper(localName = "InitResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.InitResponse")
    public java.lang.String init(
        @WebParam(name = "bAutoLogin", targetNamespace = "")
        boolean bAutoLogin,
        @WebParam(name = "in-strDBAddr", targetNamespace = "")
        java.lang.String inStrDBAddr,
        @WebParam(name = "in-strDBName", targetNamespace = "")
        java.lang.String inStrDBName,
        @WebParam(name = "in-strDBUser", targetNamespace = "")
        java.lang.String inStrDBUser,
        @WebParam(name = "in-strDBPassword", targetNamespace = "")
        java.lang.String inStrDBPassword,
        @WebParam(name = "in-strPCAddr", targetNamespace = "")
        java.lang.String inStrPCAddr,
        @WebParam(name = "in-strPCUser", targetNamespace = "")
        java.lang.String inStrPCUser,
        @WebParam(name = "in-strPCPassword", targetNamespace = "")
        java.lang.String inStrPCPassword
    );

    /**
     * Service definition of function ZMLQ__GetCardReaders
     */
    @WebResult(name = "out-structReaders", targetNamespace = "")
    @RequestWrapper(localName = "GetCardReaders", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCardReaders")
    @WebMethod(operationName = "GetCardReaders")
    @ResponseWrapper(localName = "GetCardReadersResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCardReadersResponse")
    public java.lang.String getCardReaders(
        @WebParam(name = "in-strCardNO", targetNamespace = "")
        java.lang.String inStrCardNO
    );

    /**
     * Service definition of function ZMLQ__GetACCodeAccessDuration
     */
    @WebResult(name = "out-structAccessDuration", targetNamespace = "")
    @RequestWrapper(localName = "GetACCodeAccessDuration", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetACCodeAccessDuration")
    @WebMethod(operationName = "GetACCodeAccessDuration")
    @ResponseWrapper(localName = "GetACCodeAccessDurationResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetACCodeAccessDurationResponse")
    public java.lang.String getACCodeAccessDuration(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__AddACCodeToCard
     */
    @WebResult(name = "in-strCardNO", targetNamespace = "")
    @RequestWrapper(localName = "AddACCodeToCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddACCodeToCard")
    @WebMethod(operationName = "AddACCodeToCard")
    @ResponseWrapper(localName = "AddACCodeToCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddACCodeToCardResponse")
    public java.lang.String addACCodeToCard(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__GetAllReaders
     */
    @WebResult(name = "out-structReaders", targetNamespace = "")
    @RequestWrapper(localName = "GetAllReaders", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllReaders")
    @WebMethod(operationName = "GetAllReaders")
    @ResponseWrapper(localName = "GetAllReadersResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllReadersResponse")
    public java.lang.String getAllReaders(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__AddACCodeToCompany
     */
    @WebResult(name = "in-strCompanyID", targetNamespace = "")
    @RequestWrapper(localName = "AddACCodeToCompany", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddACCodeToCompany")
    @WebMethod(operationName = "AddACCodeToCompany")
    @ResponseWrapper(localName = "AddACCodeToCompanyResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddACCodeToCompanyResponse")
    public java.lang.String addACCodeToCompany(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__RemovePerson
     */
    @WebResult(name = "in-strPersonID", targetNamespace = "")
    @RequestWrapper(localName = "RemovePerson", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemovePerson")
    @WebMethod(operationName = "RemovePerson")
    @ResponseWrapper(localName = "RemovePersonResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemovePersonResponse")
    public java.lang.String removePerson();

    /**
     * Service definition of function ZMLQ__RemoveReaderFromCard
     */
    @WebResult(name = "in-strReaderID", targetNamespace = "")
    @RequestWrapper(localName = "RemoveReaderFromCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveReaderFromCard")
    @WebMethod(operationName = "RemoveReaderFromCard")
    @ResponseWrapper(localName = "RemoveReaderFromCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveReaderFromCardResponse")
    public java.lang.String removeReaderFromCard(
        @WebParam(name = "in-strCardNO", targetNamespace = "")
        java.lang.String inStrCardNO
    );

    /**
     * Service definition of function ZMLQ__AddReaderToACCode
     */
    @WebResult(name = "in-strTimeZoneID", targetNamespace = "")
    @RequestWrapper(localName = "AddReaderToACCode", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddReaderToACCode")
    @WebMethod(operationName = "AddReaderToACCode")
    @ResponseWrapper(localName = "AddReaderToACCodeResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddReaderToACCodeResponse")
    public java.lang.String addReaderToACCode(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID,
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID
    );

    /**
     * Service definition of function ZMLQ__GetACCodeCards
     */
    @WebResult(name = "out-structCards", targetNamespace = "")
    @RequestWrapper(localName = "GetACCodeCards", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetACCodeCards")
    @WebMethod(operationName = "GetACCodeCards")
    @ResponseWrapper(localName = "GetACCodeCardsResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetACCodeCardsResponse")
    public java.lang.String getACCodeCards(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__QueryPersons
     */
    @WebResult(name = "out-structPersons", targetNamespace = "")
    @RequestWrapper(localName = "QueryPersons", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryPersons")
    @WebMethod(operationName = "QueryPersons")
    @ResponseWrapper(localName = "QueryPersonsResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryPersonsResponse")
    public java.lang.String queryPersons(
        @WebParam(name = "in-strField", targetNamespace = "")
        java.lang.String inStrField,
        @WebParam(name = "in-strOper", targetNamespace = "")
        java.lang.String inStrOper,
        @WebParam(name = "in-strValue", targetNamespace = "")
        java.lang.String inStrValue
    );

    /**
     * Service definition of function ZMLQ__GetAllBadgeTypes
     */
    @WebResult(name = "out-structBadgeTypes", targetNamespace = "")
    @RequestWrapper(localName = "GetAllBadgeTypes", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllBadgeTypes")
    @WebMethod(operationName = "GetAllBadgeTypes")
    @ResponseWrapper(localName = "GetAllBadgeTypesResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllBadgeTypesResponse")
    public java.lang.String getAllBadgeTypes(
        @WebParam(name = "in-sPersonID", targetNamespace = "")
        java.lang.String inSPersonID
    );

    /**
     * Service definition of function ZMLQ__AddCard
     */
    @WebResult(name = "in-strCompanyID", targetNamespace = "")
    @RequestWrapper(localName = "AddCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddCard")
    @WebMethod(operationName = "AddCard")
    @ResponseWrapper(localName = "AddCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddCardResponse")
    public java.lang.String addCard(
        @WebParam(name = "in-structCard", targetNamespace = "")
        java.lang.String inStructCard
    );

    /**
     * Service definition of function ZMLQ__GetAllACCodes
     */
    @WebResult(name = "out-structACCodes", targetNamespace = "")
    @RequestWrapper(localName = "GetAllACCodes", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllACCodes")
    @WebMethod(operationName = "GetAllACCodes")
    @ResponseWrapper(localName = "GetAllACCodesResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllACCodesResponse")
    public java.lang.String getAllACCodes(
        @WebParam(name = "in-strPersonID", targetNamespace = "")
        java.lang.String inStrPersonID,
        @WebParam(name = "in-strCardNO", targetNamespace = "")
        java.lang.String inStrCardNO
    );

    /**
     * Service definition of function ZMLQ__GetCardReaderTimeZones
     */
    @WebResult(name = "out-structAccessDuration", targetNamespace = "")
    @RequestWrapper(localName = "GetCardReaderTimeZones", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCardReaderTimeZones")
    @WebMethod(operationName = "GetCardReaderTimeZones")
    @ResponseWrapper(localName = "GetCardReaderTimeZonesResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCardReaderTimeZonesResponse")
    public java.lang.String getCardReaderTimeZones(
        @WebParam(name = "in-strCardNO", targetNamespace = "")
        java.lang.String inStrCardNO,
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID,
        @WebParam(name = "out-structTimeZone", targetNamespace = "")
        java.lang.String outStructTimeZone
    );

    /**
     * Service definition of function ZMLQ__GetCompanyACCodes
     */
    @WebResult(name = "out-structACCodes", targetNamespace = "")
    @RequestWrapper(localName = "GetCompanyACCodes", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCompanyACCodes")
    @WebMethod(operationName = "GetCompanyACCodes")
    @ResponseWrapper(localName = "GetCompanyACCodesResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetCompanyACCodesResponse")
    public java.lang.String getCompanyACCodes(
        @WebParam(name = "in-strCompanyID", targetNamespace = "")
        java.lang.String inStrCompanyID
    );

    /**
     * Service definition of function ZMLQ__RemoveReaderFromACCode
     */
    @WebResult(name = "in-strTimeZoneID", targetNamespace = "")
    @RequestWrapper(localName = "RemoveReaderFromACCode", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveReaderFromACCode")
    @WebMethod(operationName = "RemoveReaderFromACCode")
    @ResponseWrapper(localName = "RemoveReaderFromACCodeResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveReaderFromACCodeResponse")
    public java.lang.String removeReaderFromACCode(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID,
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID
    );

    /**
     * Service definition of function ZMLQ__GetAllTimeZones
     */
    @WebResult(name = "out-structTimeZone", targetNamespace = "")
    @RequestWrapper(localName = "GetAllTimeZones", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllTimeZones")
    @WebMethod(operationName = "GetAllTimeZones")
    @ResponseWrapper(localName = "GetAllTimeZonesResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllTimeZonesResponse")
    public java.lang.String getAllTimeZones(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID,
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID
    );

    /**
     * Service definition of function ZMLQ__RemoveACCodeFromCompany
     */
    @WebResult(name = "in-strCompanyID", targetNamespace = "")
    @RequestWrapper(localName = "RemoveACCodeFromCompany", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveACCodeFromCompany")
    @WebMethod(operationName = "RemoveACCodeFromCompany")
    @ResponseWrapper(localName = "RemoveACCodeFromCompanyResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveACCodeFromCompanyResponse")
    public java.lang.String removeACCodeFromCompany(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__ReaderControl
     */
    @Oneway
    @RequestWrapper(localName = "ReaderControl", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.ReaderControl")
    @WebMethod(operationName = "ReaderControl")
    public void readerControl(
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID,
        @WebParam(name = "nCmd", targetNamespace = "")
        int nCmd
    );

    /**
     * Service definition of function ZMLQ__RemoveACCodeFromCard
     */
    @WebResult(name = "in-strCardNO", targetNamespace = "")
    @RequestWrapper(localName = "RemoveACCodeFromCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveACCodeFromCard")
    @WebMethod(operationName = "RemoveACCodeFromCard")
    @ResponseWrapper(localName = "RemoveACCodeFromCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveACCodeFromCardResponse")
    public java.lang.String removeACCodeFromCard(
        @WebParam(name = "in-strACCodeID", targetNamespace = "")
        java.lang.String inStrACCodeID
    );

    /**
     * Service definition of function ZMLQ__GetAllPersons
     */
    @WebResult(name = "out-structPersons", targetNamespace = "")
    @RequestWrapper(localName = "GetAllPersons", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllPersons")
    @WebMethod(operationName = "GetAllPersons")
    @ResponseWrapper(localName = "GetAllPersonsResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllPersonsResponse")
    public java.lang.String getAllPersons();

    /**
     * Service definition of function ZMLQ__QueryReaders
     */
    @WebResult(name = "out-structReaders", targetNamespace = "")
    @RequestWrapper(localName = "QueryReaders", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryReaders")
    @WebMethod(operationName = "QueryReaders")
    @ResponseWrapper(localName = "QueryReadersResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryReadersResponse")
    public java.lang.String queryReaders(
        @WebParam(name = "in-strField", targetNamespace = "")
        java.lang.String inStrField,
        @WebParam(name = "in-strOper", targetNamespace = "")
        java.lang.String inStrOper,
        @WebParam(name = "in-strValue", targetNamespace = "")
        java.lang.String inStrValue
    );

    /**
     * Service definition of function ZMLQ__RemoveCard
     */
    @WebResult(name = "in-strCARDNO", targetNamespace = "")
    @RequestWrapper(localName = "RemoveCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveCard")
    @WebMethod(operationName = "RemoveCard")
    @ResponseWrapper(localName = "RemoveCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.RemoveCardResponse")
    public java.lang.String removeCard();

    /**
     * Service definition of function ZMLQ__AddPerson
     */
    @WebResult(name = "in-strPersonID", targetNamespace = "")
    @RequestWrapper(localName = "AddPerson", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddPerson")
    @WebMethod(operationName = "AddPerson")
    @ResponseWrapper(localName = "AddPersonResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddPersonResponse")
    public java.lang.String addPerson(
        @WebParam(name = "in-structPerson", targetNamespace = "")
        java.lang.String inStructPerson,
        @WebParam(name = "in-strBadgeTypeID", targetNamespace = "")
        java.lang.String inStrBadgeTypeID
    );

    /**
     * Service definition of function ZMLQ__GetAllCompanys
     */
    @WebResult(name = "out-structCompanys", targetNamespace = "")
    @RequestWrapper(localName = "GetAllCompanys", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllCompanys")
    @WebMethod(operationName = "GetAllCompanys")
    @ResponseWrapper(localName = "GetAllCompanysResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllCompanysResponse")
    public java.lang.String getAllCompanys(
        @WebParam(name = "in-strCARDNO", targetNamespace = "")
        java.lang.String inStrCARDNO
    );

    /**
     * Service definition of function ZMLQ__GetHistoryEvent
     */
    @WebResult(name = "out-structEvents", targetNamespace = "")
    @RequestWrapper(localName = "GetHistoryEvent", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetHistoryEvent")
    @WebMethod(operationName = "GetHistoryEvent")
    @ResponseWrapper(localName = "GetHistoryEventResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetHistoryEventResponse")
    public java.lang.String getHistoryEvent(
        @WebParam(name = "in-iBegin", targetNamespace = "")
        long inIBegin,
        @WebParam(name = "in-iEnd", targetNamespace = "")
        long inIEnd,
        @WebParam(name = "in-bOccurTime", targetNamespace = "")
        boolean inBOccurTime
    );

    /**
     * Service definition of function ZMLQ__QueryCards
     */
    @WebResult(name = "out-structCards", targetNamespace = "")
    @RequestWrapper(localName = "QueryCards", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryCards")
    @WebMethod(operationName = "QueryCards")
    @ResponseWrapper(localName = "QueryCardsResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.QueryCardsResponse")
    public java.lang.String queryCards(
        @WebParam(name = "in-strField", targetNamespace = "")
        java.lang.String inStrField,
        @WebParam(name = "in-strOper", targetNamespace = "")
        java.lang.String inStrOper,
        @WebParam(name = "in-strValue", targetNamespace = "")
        java.lang.String inStrValue
    );

    /**
     * Service definition of function ZMLQ__StartRecvRealEvent
     */
    @Oneway
    @RequestWrapper(localName = "StartRecvRealEvent", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.StartRecvRealEvent")
    @WebMethod(operationName = "StartRecvRealEvent")
    public void startRecvRealEvent();

    /**
     * Service definition of function ZMLQ__Uninit
     */
    @Oneway
    @RequestWrapper(localName = "Uninit", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.Uninit")
    @WebMethod(operationName = "Uninit")
    public void uninit();

    /**
     * Service definition of function ZMLQ__StopRecvRealEvent
     */
    @Oneway
    @RequestWrapper(localName = "StopRecvRealEvent", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.StopRecvRealEvent")
    @WebMethod(operationName = "StopRecvRealEvent")
    public void stopRecvRealEvent();

    /**
     * Service definition of function ZMLQ__AddReaderToCard
     */
    @WebResult(name = "in-strTEMPACCESS-END-TIME", targetNamespace = "")
    @RequestWrapper(localName = "AddReaderToCard", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddReaderToCard")
    @WebMethod(operationName = "AddReaderToCard")
    @ResponseWrapper(localName = "AddReaderToCardResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.AddReaderToCardResponse")
    public java.lang.String addReaderToCard(
        @WebParam(name = "in-strCardNO", targetNamespace = "")
        java.lang.String inStrCardNO,
        @WebParam(name = "in-strReaderID", targetNamespace = "")
        java.lang.String inStrReaderID,
        @WebParam(name = "in-strTimeZoneID", targetNamespace = "")
        java.lang.String inStrTimeZoneID,
        @WebParam(name = "in-strTEMPACCESS", targetNamespace = "")
        java.lang.String inStrTEMPACCESS,
        @WebParam(name = "in-strTEMPACCESS-START-TIME", targetNamespace = "")
        java.lang.String inStrTEMPACCESSSTARTTIME
    );

    /**
     * Service definition of function ZMLQ__GetAllCards
     */
    @WebResult(name = "out-structCards", targetNamespace = "")
    @RequestWrapper(localName = "GetAllCards", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllCards")
    @WebMethod(operationName = "GetAllCards")
    @ResponseWrapper(localName = "GetAllCardsResponse", targetNamespace = "http://tempuri.org/ZMLQ.xsd", className = "org.tempuri.zmlq.GetAllCardsResponse")
    public java.lang.String getAllCards(
        @WebParam(name = "in-sPersonID", targetNamespace = "")
        java.lang.String inSPersonID
    );
}
